-- CreateEnum
CREATE TYPE "Papel" AS ENUM ('ESCRITURA', 'DOMINIO_VIGENTE', 'HIPOTECAS_GRAVAMENES', 'CERTIFICADO_AVALUO', 'PLANO', 'CIP', 'RECEPCION_FINAL', 'POLIZA_SEGURO', 'PERMISO_EDIFICACION', 'CERTIFICADO_NUMERO', 'REGLAMENTO_COPROPIEDAD', 'SUBDIVISION_SAG', 'DERECHOS_AGUA', 'CONTRATO_ARRIENDO');

-- AlterTable
ALTER TABLE "Document" ADD COLUMN     "papel" "Papel";
